[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_forms_escrow = "8jYpZsfT5mP5LC6Fw2GhD8PjXgJHYKkNedeg85tjAvcx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
