[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_forms_escrow = "KzXK3nTcUD6KaG5aBkBmRkMy61un83K8YoQNzv72zqb"

[programs.devnet]
sol_forms_escrow = "KzXK3nTcUD6KaG5aBkBmRkMy61un83K8YoQNzv72zqb"

[programs.mainnet]
sol_forms_escrow = "KzXK3nTcUD6KaG5aBkBmRkMy61un83K8YoQNzv72zqb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
